### ISSUE TITLE
Es fehlt requirments.txt und die python version mit der entwickelt wird.

### ISSUE THREAD

**Issue by JohnBioinf** [LFT-W47/UFZ-Flask#1]
Du musst angeben, mit welcher Python-Version wir entwickeln. Die erste Stelle reicht also z.B. 3.10. Packs in README.md erstmal.
Außerdem "weiß" ich nicht, welche Packages ich brauche, um deine Anwendung zu starten. Das ist jetzt trivial, sollte aber so bleiben.
Mach dir dafür eine eigene Python env, sonst kommt noch der ganze Kram dazu, den du vielleicht lokal installiert hast.

```
$ python app.py 
Traceback (most recent call last):
  File "/home/andersj/git/UFZ-Flask/app.py", line 1, in <module>
    from flask import Flask, render_template
ModuleNotFoundError: No module named 'flask'
```

**Comment by LFT-W47** [comment]
Hi John, hab eine Readme erstellt und die nötigen packages aus der conda env gezogen die ich genutzt habe. Main wurde geupdated

**Comment by JohnBioinf** [comment]
Siehe merge request.
