### ISSUE TITLE
HTML-Seite abstrahieren

### ISSUE THREAD

**Issue by JohnBioinf** [LFT-W47/UFZ-Flask#3]
Du solltest einmal den Inhalt einer Seite von der gesamten Website entkoppeln.
Du definierst also einmal die Website mit Header, Body usw. und dann hast du ein base_layout.html:

```
<!doctype html>
<html lang="en" style="min-height: 100%">
...
{% block content %}
{% endblock %}
```

Die einzelnen Seiten definieren dies dann mit

```
{% extends "base_layout.html" %}
{% block content %}
<content>
{% endblock %}
```

Dies erleichtert später das Hinzufügen von Elementen (Footer, Topbar, etc.), die für alle gleich sein sollen.

**Comment by LFT-W47** [comment]
Erledigt
